# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-08-29 11:23
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=0, verbose_name='逻辑删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('image', models.CharField(max_length=128, verbose_name='图片链接')),
                ('target', models.CharField(max_length=128, verbose_name='跳转链接')),
                ('sequence', models.IntegerField(choices=[(1, 'FIRST'), (2, 'SECOND'), (3, 'THIRD'), (4, 'FOUTH'), (5, 'FIFTH')], verbose_name='序号')),
            ],
            options={
                'verbose_name_plural': '轮播图',
                'verbose_name': '轮播图',
                'db_table': 'carousels',
            },
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=0, verbose_name='逻辑删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=10, unique=True, verbose_name='分类名称')),
                ('sequence', models.IntegerField(choices=[(1, 'FIRST'), (2, 'SECOND'), (3, 'THIRD'), (4, 'FOUTH'), (5, 'FIFTH'), (6, 'SIXTH')], verbose_name='序号')),
            ],
            options={
                'verbose_name_plural': '头条分类',
                'verbose_name': '头条分类',
                'db_table': 'headlines_categories',
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=128, verbose_name='评论内容')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('child_counts', models.IntegerField(default=0, verbose_name='子评论数量')),
            ],
            options={
                'verbose_name_plural': '评论',
                'verbose_name': '评论',
                'db_table': 'headlines_comments',
            },
        ),
        migrations.CreateModel(
            name='Headlines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=0, verbose_name='逻辑删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('title', models.CharField(max_length=64, verbose_name='头条标题')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='头条内容')),
                ('image', models.CharField(default=None, max_length=128, null=True, verbose_name='头条图片链接')),
                ('comment_counts', models.IntegerField(default=0, verbose_name='头条评论数')),
                ('click_counts', models.IntegerField(default=0, verbose_name='浏览量')),
                ('status', models.IntegerField(choices=[(-1, 'UNAPPROVED'), (0, 'CHECKING'), (1, 'APPROVED')], default=0, verbose_name='头条状态')),
                ('reason', models.CharField(default=None, max_length=40, null=True, verbose_name='未通过审核原因')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='作者')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='headlines.Categories', verbose_name='头条分类')),
            ],
            options={
                'verbose_name_plural': '头条',
                'verbose_name': '头条',
                'db_table': 'headlines',
            },
        ),
        migrations.CreateModel(
            name='HeadlinesCollections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=0, verbose_name='逻辑删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('headlines', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='headlines.Headlines', verbose_name='头条')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name_plural': '头条收藏',
                'verbose_name': '头条收藏',
                'db_table': 'user_headlines_collections',
            },
        ),
        migrations.AddField(
            model_name='comments',
            name='headlines',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='headlines.Headlines', verbose_name='头条'),
        ),
        migrations.AddField(
            model_name='comments',
            name='parent',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='headlines.Comments', verbose_name='父评论'),
        ),
        migrations.AddField(
            model_name='comments',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
    ]
