# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-08-29 11:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questions', '0001_initial'),
        ('headlines', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='headlineslabel',
            name='label',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.AskLables', verbose_name='头条标签'),
        ),
        migrations.AddField(
            model_name='headlinescollections',
            name='headlines',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='headlines.Headlines', verbose_name='头条'),
        ),
    ]
