# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-08-29 11:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('headlines', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BroswingHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=0, verbose_name='逻辑删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('headlines', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='headlines.Headlines', verbose_name='浏览记录')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name_plural': '浏览记录',
                'db_table': 'broswing_history',
                'verbose_name': '浏览记录',
            },
        ),
        migrations.CreateModel(
            name='HeadlinesLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=0, verbose_name='逻辑删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('headline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='headlines.Headlines', verbose_name='头条标签')),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.AskLables', verbose_name='头条标签')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='headlines',
            name='labels',
            field=models.ManyToManyField(related_name='headlines', through='headlines.HeadlinesLabel', to='questions.AskLables'),
        ),
    ]
