# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-08-29 11:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=0, verbose_name='逻辑删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('content', models.TextField(verbose_name='回答的评论内容')),
                ('status', models.SmallIntegerField(default=0, verbose_name='状态')),
                ('useful_count', models.IntegerField(default=0, verbose_name='回答有用')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='回答人')),
            ],
            options={
                'verbose_name_plural': '我的回答',
                'verbose_name': '我的回答',
                'db_table': 'answers',
            },
        ),
        migrations.CreateModel(
            name='AnswersComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=0, verbose_name='逻辑删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('content', models.CharField(max_length=128, verbose_name='评论内容')),
                ('status', models.SmallIntegerField(default=0, verbose_name='状态')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.Answers', verbose_name='评论的回答')),
                ('parent', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='questions.AnswersComments', verbose_name='评论的父类')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='评论用户')),
            ],
            options={
                'verbose_name_plural': '用户评论',
                'verbose_name': '用户评论',
                'db_table': 'answers_comments',
            },
        ),
        migrations.CreateModel(
            name='AnswersUseful',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=0, verbose_name='逻辑删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.Answers', verbose_name='有用的回答')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name_plural': '回答有用',
                'verbose_name': '回答有用',
                'db_table': 'answers_useful',
            },
        ),
        migrations.CreateModel(
            name='AskLables',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=0, verbose_name='逻辑删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=20, verbose_name='名称')),
                ('focus_count', models.IntegerField(default=0, verbose_name='关注数')),
                ('sequence', models.IntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'verbose_name_plural': '标签',
                'verbose_name': '标签',
                'db_table': 'ask_lables',
            },
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=0, verbose_name='逻辑删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('title', models.CharField(max_length=128, verbose_name='标题')),
                ('detail', models.TextField(verbose_name='问题详情')),
                ('answers_count', models.IntegerField(verbose_name='回答数')),
                ('useful_count', models.IntegerField(default=0, verbose_name='有用数')),
                ('click_count', models.IntegerField(default=0, verbose_name='点击量')),
                ('status', models.SmallIntegerField(default=0, verbose_name='状态')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作者')),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.AskLables', verbose_name='标签')),
            ],
            options={
                'verbose_name_plural': '问题',
                'verbose_name': '问题',
                'db_table': 'questions',
            },
        ),
        migrations.CreateModel(
            name='QuestionUseful',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=0, verbose_name='逻辑删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('questions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.Questions', verbose_name='问题')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name_plural': '问题有用',
                'verbose_name': '问题有用',
                'db_table': 'question_useful',
            },
        ),
        migrations.AddField(
            model_name='answers',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.Questions', verbose_name='回答的问题'),
        ),
    ]
