# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-08-29 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asklables',
            name='intro',
            field=models.CharField(default=1, max_length=256, verbose_name='标签简介'),
            preserve_default=False,
        ),
    ]
