# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-08-29 15:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questions', '0002_asklables_intro'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabelFocus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=0, verbose_name='逻辑删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.AskLables', verbose_name='关注的标签')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='关注的用户')),
            ],
            options={
                'db_table': 'label_focus',
                'verbose_name': '标签关注',
                'verbose_name_plural': '标签关注',
            },
        ),
    ]
